//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildEntitlement
    {
        public int ID { get; set; }
        public Nullable<int> ChildID { get; set; }
        public Nullable<int> EntitlementID { get; set; }
    
        public virtual Child Child { get; set; }
        public virtual Entitlement Entitlement { get; set; }
    }
}
