//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TafToTafEntities1 : DbContext
    {
        public TafToTafEntities1()
            : base("name=TafToTafEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Child> Children { get; set; }
        public virtual DbSet<ChildKinderGarden> ChildKinderGardens { get; set; }
        public virtual DbSet<Kind> Kinds { get; set; }
        public virtual DbSet<KinderGarden> KinderGardens { get; set; }
        public virtual DbSet<KindUser> KindUsers { get; set; }
        public virtual DbSet<Professional> Professionals { get; set; }
        public virtual DbSet<ProfessionKind> ProfessionKinds { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<Calander> Calanders { get; set; }
    }
}
