//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professional
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ProfessionKind { get; set; }
        public Nullable<int> NumHourWork { get; set; }
        public Nullable<int> NumDaysWork { get; set; }
        public Nullable<bool> Sunday { get; set; }
        public Nullable<bool> Monday { get; set; }
        public Nullable<bool> Thuesday { get; set; }
        public Nullable<bool> Wednesday { get; set; }
        public Nullable<bool> Tursday { get; set; }
        public Nullable<int> userID { get; set; }
    
        public virtual ProfessionKind ProfessionKind1 { get; set; }
        public virtual User User { get; set; }
    }
}
