//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professional
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Professional()
        {
            this.Calanders = new HashSet<Calander>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ProfessionKind { get; set; }
        public Nullable<int> NumHourWork { get; set; }
        public Nullable<int> NumDaysWork { get; set; }
        public Nullable<bool> Sunday { get; set; }
        public Nullable<bool> Monday { get; set; }
        public Nullable<bool> Thuesday { get; set; }
        public Nullable<bool> Wednesday { get; set; }
        public Nullable<bool> Tursday { get; set; }
        public Nullable<int> userID { get; set; }
    
        public virtual ProfessionKind ProfessionKind1 { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calander> Calanders { get; set; }
    }
}
